# Generated by Django 4.1.7 on 2023-03-03 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_customer_options_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.CharField(default='te', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='username',
            field=models.CharField(default='sa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
